apiVersion: v1
kind: Service
metadata:
  name: {{ include "challenger-helm.fullname" . }}
  labels:
    {{- include "challenger-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.targetPort }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "challenger-helm.selectorLabels" . | nindent 4 }}

